### ISSUE TITLE
Seg fault going through DecodeIntoRGBA with DisableFancyUpsampling = true

### ISSUE THREAD

**Issue by gaillard** [pixiv/go-libjpeg#36]
When I leave DisableFancyUpsampling to false it is fine.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f6c467b5eb7]

runtime stack:
runtime.throw(0x616bd5, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 11 [syscall, locked to thread]:
runtime.cgocall(0x5a6260, 0xc42004fcb0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42004fc68 sp=0xc42004fc28
NAME/vendor/github.com/pixiv/go-libjpeg/jpeg._Cfunc_jpeg_read_scanline(0x7f6c380008c0, 0xc4200bc000, 0x2, 0x0)
	??:0 +0x4d fp=0xc42004fcb0 sp=0xc42004fc68
NAME/vendor/github.com/pixiv/go-libjpeg/jpeg.readScanLines(0x7f6c380008c0, 0xc4200bc000, 0x16e3600, 0x16e3600, 0x2ee0)
	/home/gaillard/go/src/NAME/vendor/github.com/pixiv/go-libjpeg/jpeg/decompress.go:305 +0x120 fp=0xc42004fd00 sp=0xc42004fcb0
NAME/vendor/github.com/pixiv/go-libjpeg/jpeg.DecodeIntoRGBA(0x8ec580, 0xc42002e020, 0xc42004fdd8, 0xc42009e000, 0x0, 0x0)
	/home/gaillard/go/src/NAME/vendor/github.com/pixiv/go-libjpeg/jpeg/decompress.go:297 +0x33d fp=0xc42004fda0 sp=0xc42004fd00

... lines from our code ...
```

Nice library, is this a known issue?

I'm testing this on amd64 on version 1.5.1 of libjpeg-turbo.

**Comment by harukasan** [comment]
@gaillard Could you tell me some code to reproduce this issue?

**Comment by gaillard** [comment]
```
package main

import (
	stdimage "image"
	"image/color"
	"io/ioutil"
	"math/rand"
	"os"

	libjpeg "github.com/pixiv/go-libjpeg/jpeg"
)

func main() {
	src := randomImage(3000, 2000)

	f, err := ioutil.TempFile("", "issue_")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(f.Name())

	encErr := libjpeg.Encode(f, src, &libjpeg.EncoderOptions{Quality: 95})
	closeErr := f.Close()
	if encErr != nil || closeErr != nil {
		panic(err)
	}

	ff, err := os.Open(f.Name())
	if err != nil {
		panic(err)
	}
	defer ff.Close()

	//UNCOMMENT FOR BOOM !
	_, err = libjpeg.DecodeIntoRGBA(ff, &libjpeg.DecoderOptions{DisableBlockSmoothing: true /*, DisableFancyUpsampling: true*/})
	if err != nil {
		panic(err)
	}
}

func randomImage(w, h int) stdimage.Image {
	img := stdimage.NewRGBA(stdimage.Rect(0, 0, w, h))
	for x := 0; x < w; x += 2 {
		for y := 0; y < h; y += 2 {
			img.Set(x, y, color.RGBA{R: uint8(rand.Intn(255)), G: uint8(rand.Intn(255)), B: uint8(rand.Intn(255)), A: uint8(rand.Intn(255))})
		}
	}
	return img
}

```

**Comment by gaillard** [comment]
I am also getting another seg fault going through DecodeConfig, maybe unrelated. I don't have a test case for that one though, just the stack.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f6f88000388 pc=0x7f6f88000388]

runtime stack:
runtime.throw(0x1a7eb53, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 49 [syscall, locked to thread]:
runtime.cgocall(0xbea500, 0xc420349638, 0xc400000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420349608 sp=0xc4203495c8
NAME/vendor/github.com/pixiv/go-libjpeg/jpeg._Cfunc_new_decompress(0x0)
	??:0 +0x4a fp=0xc420349638 sp=0xc420349608
NAME/vendor/github.com/pixiv/go-libjpeg/jpeg.DecodeConfig(0x25127e0, 0xc4202a20e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gaillard/go/src/NAME/vendor/github.com/pixiv/go-libjpeg/jpeg/decompress.go:323 +0xa4 fp=0xc420349688 sp=0xc420349638
```

**Comment by harukasan** [comment]
I'll working about `DecodeConfig` in the next week.
